.codeclimate.yml, .landscape.yml
=> Add configuration for landscape, codeclimate integrations

MANIFEST.in, requirements.txt, requirements_dev.txt, setup.py
Improvement of the setup and requirements:
- added requirements.txt
- automatically use requirements_dev.txt for setup and test requirements
- plus small changes
=> Setup impr

requirements.txt, tests/test_minimizer.py, zfit/__init__.py, zfit/core/minimizer.py, zfit/core/parameter.py, zfit/minimize.py, zfit/minimizers/base_tf.py, zfit/minimizers/minimizer_minuit.py, zfit/minimizers/minimizer_tfp.py, zfit/minimizers/minimizers_scipy.py, zfit/minimizers/optimizers_tf.py, zfit/minimizers/state.py, zfit/util/exception.py, zfit/util/ztyping.py
WIP!
- MinuitMinimizer works already for minimization
- MinimizerInterface is implemented (`abc.abstractmethod` is mandatory to override)
- BaseMinimizer takes care of the public functions and allows for simple minimizer subclassing
- TF optimizer getting wrapped instead of subclassed
@apuignav @rsilvaco is this what you would have expected?
=> create Base minimizer and API

README.rst
Adjust in the readme the license
=> Fix license in readme

tests/test_basePDF.py, zfit/core/basepdf.py, zfit/pdfs/dist_tfp.py
Reverts zfit/zfit#55.
I pressed the wrong button.
=> Revert "WIP: Add gradient to basepdf"

README.rst, tests/test_pdfs.py, zfit/pdfs/functor.py
=> Fix sum pdf

requirements.txt, zfit/core/data.py, zfit/pdfs/functor.py
This is the working branch to implement dataset
=> add Dataset

legacy/optimization.py, tests/test_basePDF.py, tests/test_loss.py, tests/test_pdfs.py, zfit/__init__.py, zfit/constraint.py, zfit/core/basefunc.py, zfit/core/basemodel.py, zfit/core/basepdf.py, zfit/core/data.py, zfit/core/integration.py, zfit/core/loss.py, zfit/core/math.py, zfit/core/parameter.py, zfit/core/sample.py, zfit/core/tfext.py, zfit/loss.py, zfit/models/functor.py, zfit/old_ztf.py, zfit/settings.py, zfit/util/container.py, zfit/util/exception.py, zfit/ztf/__init__.py, zfit/ztf/wrapping_tf.py, zfit/ztf/zextension.py
Refactored constraints to take a Tensor (makes it more flexible) and added `zfit.constraint.nll_gaussian`.
Added `ExtendedUnbinnedNLL`
=> Constraints and Loss refactoring

zfit/minimizers/fitresult.py
=> Add accessor to converged.

tests/test_dimensions.py, tests/test_functor_pdf.py, tests/test_minimizer.py, zfit/core/limits.py, zfit/models/basefunctor.py
Allows to combine (expand dims) and add (only if obs are the same) limits.
Also updated functors to use the limits directly
=> Combine and add spaces

tests/test_parameter.py, zfit/core/basemodel.py, zfit/core/parameter.py
=> Clean names

tests/test_basePDF.py, tests/test_cache.py, tests/test_loss.py, zfit/core/basemodel.py, zfit/core/data.py, zfit/core/interfaces.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/minimizers/baseminimizer.py, zfit/minimizers/interface.py, zfit/minimizers/minimizer_minuit.py, zfit/util/cache.py
Primitive caching is implemented, MinuitMinimizer uses now cached gradient
=> Implement Caching

tests/test_dimensions.py, tests/test_functor_pdf.py, zfit/core/basefunc.py, zfit/core/basemodel.py, zfit/core/baseobject.py, zfit/core/basepdf.py, zfit/core/data.py, zfit/core/dimension.py, zfit/core/limits.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/models/basic.py, zfit/models/dist_tfp.py, zfit/models/physics.py
Solves #82 
Add a _N_OBS in Dimensional and check
=> Catch wrong n_obs

examples/cb_example.py, tests/test_basePDF.py, tests/test_pdfs.py, zfit/core/basefunc.py, zfit/core/basemodel.py, zfit/core/baseobject.py, zfit/core/basepdf.py, zfit/core/integration.py, zfit/core/interfaces.py, zfit/core/operations.py, zfit/core/parameter.py, zfit/minimizers/base_tf.py, zfit/minimizers/baseminimizer.py, zfit/minimizers/minimizers_scipy.py, zfit/models/basic.py, zfit/models/dist_tfp.py, zfit/models/functions.py, zfit/models/functor.py, zfit/models/physics.py, zfit/models/special.py
So, as once discussed back, I changed now (nearly) all "parameters" to "params" (Except of the class, it is still zfit.Parameter).
How do you like it? It does not look as nice, though the added compactness without the loss of readability still convinces me.
What's your opinion about it @apuignav ?
=> Breaking Change: all "parameters" to "params"

tests/test_dimensions.py, zfit/core/limits.py
=> Add `__mul__` is combine for spaces

tests/test_basePDF.py, tests/test_space.py, zfit/core/basemodel.py, zfit/core/dimension.py, zfit/core/limits.py, zfit/core/sample.py
Safe sampling with multiple limits is now supported
=> Multiple limits sampling

tests/test_parameter.py, zfit/core/parameter.py
=> Expand capabilities of dealing with complex parameters

tests/test_basePDF.py, tests/test_integrate.py, tests/test_operations.py, tests/test_pdfs.py, zfit/core/basemodel.py, zfit/core/basepdf.py, zfit/core/dimension.py, zfit/core/integration.py, zfit/core/interfaces.py, zfit/core/limits.py, zfit/core/operations.py, zfit/models/basefunctor.py, zfit/models/dist_tfp.py, zfit/models/functions.py, zfit/models/functor.py, zfit/models/special.py, zfit/pdf.py, zfit/ztf/zextension.py
To start reviewing, tests still missing.
=> Add create_projection_pdf

tests/test_basePDF.py, tests/test_data.py, tests/test_extended.py, tests/test_integrate.py, tests/test_loss.py, tests/test_parameter.py, tests/test_pdfs.py, tests/test_sampling.py, tests/test_simple_subclass.py, zfit/core/basemodel.py, zfit/core/basepdf.py, zfit/core/data.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/core/sample.py, zfit/models/basic.py, zfit/models/dist_tfp.py, zfit/models/functor.py, zfit/models/physics.py, zfit/sample.py, zfit/util/container.py, zfit/util/ztyping.py, zfit/ztf/wrapping_tf.py
=> Sample data

tests/test_data.py, zfit/core/data.py, zfit/core/limits.py
Add `from_pandas` and `to_pandas` function. This allows for simple preprocessing: load `from_root`, do `to_pandas`, preprocess, `from_pandas`
Sure, more overhead than doing it manually with uproot + pandas, but it works
=> Pandas data

tests/test_sampling.py, zfit/core/basemodel.py, zfit/core/data.py, zfit/core/sample.py, zfit/util/ztyping.py
Add the possibility to provide a custom `sample_and_weight` function
=> Importance sampling

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.rst
Very small change, but we can use this as guideline for `zfit-physics`. Anything else that should be added in the guidelines? Coding standards maybe?
=> Small update in CONTRIBUTING guidelines

zfit/core/parameter.py, zfit/util/execution.py
Add small hack to prevent autoconversion
=> Hack autoconversion params

tests/test_pdf_cb.py, zfit/models/physics.py
@apuignav @mayou36   
Do you want me to also create the PDF class for the `DoubleCrystallBall`?
=> add double_crystalball_func to zfit/models/physics

tests/test_basePDF.py, tests/test_cache.py, tests/test_data.py, tests/test_dimensions.py, tests/test_execution.py, tests/test_extended.py, tests/test_functor_pdf.py, tests/test_graph.py, tests/test_integrate.py, tests/test_loss.py, tests/test_minimizer.py, tests/test_operations.py, tests/test_parameter.py, tests/test_pdf_cb.py, tests/test_pdf_normal.py, tests/test_pdfs.py, tests/test_sampling.py, tests/test_simple_subclass.py, tests/test_space.py, tests/test_temporary.py, tests/test_tfext.py, tests/test_weights.py, zfit/core/testing.py
Use setup and teardown methods to reset the graph and session before every test
=> Test setups

tests/test_basePDF.py, tests/test_loss.py, tests/test_pdf_kde.py, zfit/core/basepdf.py, zfit/core/data.py, zfit/core/integration.py, zfit/models/dist_tfp.py, zfit/ztf/zextension.py
Improve dist_tfp to allow for distribution args that are not parameters.
Fix shape of TFP distributions (wrapped)
=> WIP: Fix tfp distribution shape

setup.py, zfit/__init__.py
=> new release 0.3.2

tests/test_fitresult.py, zfit/minimizers/fitresult.py
Add covariance method in `FitResult`. Takes `params` as argument, and `as_dict` to return a dictionary.
None yet, Is there a place where the `FitResult` ( I didn't find it.) ? If not I will just create a test file.
=> Add covariance method the FitResult.

docs/loss.rst, docs/model.rst
I fixed typos and I changed parts that didn't look nice in the doc for the constraints.
See https://zfit.github.io/zfit/model.html, and https://zfit.github.io/zfit/loss.html.
=> Changes in doc for the new constraint classes

tests/test_loss.py, tests/test_pdf_polynomials.py, zfit/core/basemodel.py, zfit/core/integration.py, zfit/models/polynomials.py, zfit/pdf.py, zfit/util/ztyping.py
=> Polynomials from recurrence relations.

CHANGELOG.rst, tests/test_sampling.py, zfit/core/sample.py, zfit/models/dist_tfp.py
- Adds (finally!) analytic sampling by default for the TFP distributions
=> Add analytic sampling for distributions

CHANGELOG.rst, tests/test_constraint.py, zfit/core/constraint.py
Fixes #162 
-
- test for three parameters and Gaussian constraint
=> Fix gauss constr

setup.py
Cleanup setup.py to make conda deployment possible
=> Remove unnecessary packages from setup_requirements

.git_archival.txt, .gitattributes, requirements_dev.txt, setup.py, zfit/__init__.py
Adds versioning automatic with SCM
=> Scm versioning

CHANGELOG.rst, tests/test_parameter.py, zfit/__init__.py, zfit/core/parameter.py, zfit/param.py
Fixes fixed parameters in https://github.com/zfit/zfit-development/issues/39
=> constant parameter

zfit/models/functions.py
=> Api cleanup

README.rst
=> Nicer badge

zfit/core/loss.py
untested
unrelated (and unimportant), but i'd not use a double negation in anything (in this case `IntentionNotUnambiguousError` -> `IntentionAmbiguousError`)
=> fix error message in core/loss.py

CHANGELOG.rst, tests/test_minimizer.py, tests/test_pdf_cb.py, zfit/__init__.py, zfit/core/basemodel.py, zfit/core/basepdf.py, zfit/core/data.py, zfit/core/interfaces.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/minimizers/baseminimizer.py, zfit/minimizers/fitresult.py, zfit/minimizers/minimizer_minuit.py, zfit/minimizers/minimizer_tfp.py, zfit/models/physics.py, zfit/util/ztyping.py, zfit/z/zextension.py
=> Cb test fail

setup.py, tests/test_data.py, zfit/__init__.py, zfit/constraint.py, zfit/core/interfaces.py, zfit/minimize.py, zfit/models/physics.py, zfit/z/tools.py, zfit/z/wrapping_tf.py, zfit/z/zextension.py
=> Remove commented-out code

.travis.yml, CHANGELOG.rst, tests/test_data.py, tests/test_fitresult.py, tests/test_loss.py, zfit/core/data.py, zfit/core/space.py, zfit/util/exception.py, zfit/z/zextension.py
Fixes #193 
- fix wrong length of weights, as not cut
- test to see if weights are correct
=> WIP: Fix weights shape wrong with cut data

CHANGELOG.rst, tests/test_integrate.py, tests/test_parameter.py, zfit/core/parameter.py, zfit/param.py, zfit/util/exception.py
Fixes #198 
- add method `set_values`
- jep
=> Implement `set_values`

tests/test_cache.py, tests/test_graph.py, zfit/util/cache.py, zfit/z/zextension.py
=> Fix cache not invalidated

tests/test_basePDF.py, tests/test_fitresult.py, tests/test_pdfs.py, zfit/core/basefunc.py, zfit/core/basemodel.py, zfit/core/basepdf.py, zfit/core/constraint.py, zfit/core/integration.py, zfit/core/loss.py, zfit/core/sample.py, zfit/core/testing.py, zfit/settings.py, zfit/util/ztyping.py, zfit/z/random.py, zfit/z/wrapping_tf.py, zfit/z/zextension.py
=> Cleanup tf1

tests/test_parameter.py, zfit/core/interfaces.py, zfit/core/parameter.py, zfit/core/testing.py, zfit/minimizers/base_tf.py, zfit/minimizers/minimizer_minuit.py, zfit/minimizers/minimizers_scipy.py, zfit/util/temporary.py, zfit/z/unstable.py
Fixes #
- Refactoring of params, cleanup
-
-
-
-
-
=> Cleanup params

CHANGELOG.rst, tests/test_cache.py, tests/test_constraint.py, tests/test_graph.py, tests/test_minimizer.py, tests/test_z.py, zfit/__init__.py, zfit/core/basemodel.py, zfit/core/basepdf.py, zfit/core/data.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/core/sample.py, zfit/core/space.py, zfit/core/testing.py, zfit/minimizers/fitresult.py, zfit/minimizers/minimizer_minuit.py, zfit/minimizers/minimizer_tfp.py, zfit/models/physics.py, zfit/models/polynomials.py, zfit/sample.py, zfit/settings.py, zfit/util/cache.py, zfit/util/execution.py, zfit/util/graph.py, zfit/z/random.py, zfit/z/wrapping_tf.py, zfit/z/zextension.py
- simple eager mode
- cache invalidation
- specific methods for graph/not graph
- check that invalidation of graph works
-
-
=> rework and extend Jit

CHANGELOG.rst, tests/test_space.py, zfit/core/space.py
=> Fix with_coords dropping axes

CHANGELOG.rst, zfit/minimize.py, zfit/minimizers/baseminimizer.py, zfit/minimizers/minimizer_minuit.py
Catch if error due to NaN is raised, add pushback as default strategy
=> Catch minimizer strategy if NaN is raised by TF

docs/getting_started.rst, docs/intro/model.rst, examples/plot_sig_bkg.py, examples/signal_bkg_mass_fit.py, tests/test_operations.py, tests/test_pdf_sumpdf.py, tests/test_pdfs.py, tests/test_sampling.py, zfit/core/basefunc.py, zfit/core/basemodel.py, zfit/core/baseobject.py, zfit/core/basepdf.py, zfit/core/integration.py, zfit/core/interfaces.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/core/sample.py, zfit/exception.py, zfit/minimizers/baseminimizer.py, zfit/minimizers/interface.py, zfit/minimizers/optimizers_tf.py, zfit/models/basefunctor.py, zfit/models/basic.py, zfit/models/dist_tfp.py, zfit/models/functions.py, zfit/models/functor.py, zfit/models/polynomials.py, zfit/util/exception.py, zfit/z/random.py
- make exceptions public in`zfit.exceptions`
- more fine-grained control with more specific exceptions
- sampling test with multiple limits
=> WIP: exceptions

CHANGELOG.rst, examples/signal_bkg_mass_fit.py, requirements.txt, tests/test_fitresult.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/minimize.py, zfit/minimizers/baseminimizer.py, zfit/minimizers/fitresult.py, zfit/util/execution.py, zfit/util/legacy.py, zfit/z/wrapping_tf.py
- Add nice `__str__` for FitResult, params
- add `set_values` with FitResult, to take the values from there
-
- `set_values` fed with FitResult
-
-
=> Params repr

CHANGELOG.rst, docs/intro/parameter.rst, tests/test_parameter.py, zfit/core/parameter.py
- value_fn now takes arguments
-
-
- Test with arguments
=> Use `value_fn` with args of ComposedParameter

CHANGELOG.rst, docs/intro/parameter.rst, tests/test_cache.py, tests/test_constraint.py, tests/test_dependencies.py, tests/test_dependents.py, tests/test_loss.py, tests/test_math.py, tests/test_parameter.py, zfit/core/basemodel.py, zfit/core/baseobject.py, zfit/core/basepdf.py, zfit/core/constraint.py, zfit/core/data.py, zfit/core/dependents.py, zfit/core/interfaces.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/minimizers/baseminimizer.py, zfit/minimizers/minimizer_minuit.py, zfit/models/basefunctor.py, zfit/models/functions.py, zfit/util/cache.py
Improve `get_params` function
- returns now all parameters needed, recursively as well
- one test with many combinations
=> Params deps

CHANGELOG.rst, tests/test_basePDF.py, tests/test_pdfs.py, zfit/core/basepdf.py
Fixes #
- add `ext_*` methods that automatically scale by the yield
- test if value is extended
=> Add ext_method

CHANGELOG.rst, examples/custom_pdf_advanced.py, examples/signal_bkg_mass_extended_fit.py, tests/test_constraint.py, tests/test_fitresult.py, tests/test_loss.py, tests/test_sampling.py, zfit/core/baseobject.py, zfit/core/constraint.py, zfit/core/dimension.py, zfit/core/interfaces.py, zfit/core/loss.py, zfit/core/sample.py, zfit/minimizers/fitresult.py, zfit/models/basic.py, zfit/models/physics.py, zfit/sample.py, zfit/settings.py, zfit/util/exception.py, zfit/util/execution.py, zfit/util/warnings.py
Make loss parametrized with the new base class to also have `get_params`
- added in loss tests to test params returned
=> parametrized loss

.travis.yml, CHANGELOG.rst, requirements.txt, tests/test_basePDF.py, tests/test_minimizer.py, zfit/__init__.py, zfit/core/basemodel.py, zfit/core/integration.py, zfit/core/parameter.py, zfit/core/sample.py, zfit/core/space.py, zfit/core/testing.py, zfit/minimizers/minimizer_minuit.py, zfit/models/basic.py, zfit/util/ztyping.py, zfit/z/__init__.py, zfit/z/random.py, zfit/z/zextension.py
- apply shift on the fly for exp
=> Expon shift

CHANGELOG.rst, zfit/core/integration.py, zfit/core/sample.py
Fixes #
- Samples correctly even if a max is found later on
=> Add correct sampling

CHANGELOG.rst, zfit/models/dist_tfp.py
Should fix the shape problems with partial integration
=> Tfp dist data

.travis.yml, CHANGELOG.rst, tests/test_basePDF.py, tests/test_integrate.py, tests/test_loss.py, tests/test_pdf_polynomials.py, tests/test_pdfs.py, tests/test_sampling.py, zfit/models/functor.py
Fixes integral failing (partial)
=> Fix partial integration and broadcasting of composite PDFs

zfit/models/kde.py
=> add kdeV1 1 dim

CHANGELOG.rst, zfit/core/sample.py
Makes sure the sampling is unbiased by increasing the accept-reject minimum sample
=> Add minimum sampling in accept reject

CHANGELOG.rst, README.rst
=> Update CHANGELOG.rst and docs version for release

docs/getting_started/examples.rst
=> Removed Typo

CHANGELOG.rst, requirements.txt, tests/test_minimizer.py, tests/test_parameter.py, zfit/core/baseobject.py, zfit/core/basepdf.py, zfit/core/data.py, zfit/core/interfaces.py, zfit/core/parameter.py, zfit/minimizers/minimizer_tfp.py, zfit/models/functor.py, zfit/util/__init__.py, zfit/util/deprecation.py, zfit/util/legacy.py, zfit/z/random.py
Upgrade to TF23
Fixes parameters: new tensor conversion function in TF
=> upgrade to tf23

CHANGELOG.rst, tests/test_constraint.py, zfit/constraint.py, zfit/core/constraint.py
- Add Poissonian constraint
- test poisson constraint value against scipy
=> Add Poisson constraint

tests/binnednll.py, zfit/_loss/__init__.py, zfit/_loss/binnedloss.py, zfit/core/binneddata.py, zfit/core/binnedpdf.py, zfit/core/interfaces.py, zfit/loss.py
=> add binned NLL

requirements.txt, tests/test_data.py, zfit/core/data.py
=> Upgrade to uproot4 and add in requirements.txt

CHANGELOG.rst, requirements.txt, tests/test_loss.py, tests/test_minimizer.py
=> Upgrade to tf 2.4 in requirements.txt

docs/getting_started/5_minutes_to_zfit.rst
- Correct some typos and phrasings.
- Update some code snippets that either don't work anymore or are no longer best practice.
- Add a paragraph explaining that Parameters are mutable.
=> Update 5-minutes-to-zfit article.

CHANGELOG.rst, docs/getting_started/5_minutes_to_zfit.rst, tests/test_pdf_fftconv.py, zfit/models/convolution.py
Fixes #291 
- remove the shift
- added error from issue, all interpolations
=> fix shift in convFFT with asymetric kernel

examples/simple_fit.py, requirements.txt, tests/__init__.py, tests/test_graph.py, tests/test_pdf_conditional.py, tests/test_pdf_fftconv.py, tests/test_sampling.py, utils/api/argdocs.yaml, zfit/__init__.py, zfit/core/basemodel.py, zfit/core/baseobject.py, zfit/core/basepdf.py, zfit/core/interfaces.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/models/basic.py, zfit/models/conditional.py, zfit/pdf.py, zfit/settings.py, zfit/util/container.py, zfit/util/execution.py, zfit/z/random.py
Fixes #135 
- Add a simple conditional PDF by setting the parameter values.
- simple test
=> add first version of conditional PDF

CHANGELOG.rst, zfit/core/data.py, zfit/core/sample.py, zfit/models/convolution.py, zfit/models/functor.py
=> fix: randomize sum sampling

zfit/z/const.py
Could not find any usage of this file in the project.
I searched via
- usage search with pycharm
- greping for an import statement
- running test suite with coverage.
=> Remove unused python module zfit.z.const.

CHANGELOG.rst, tests/test_loss.py, tests/test_minimizer.py, zfit/core/data.py, zfit/core/loss.py
- running minimization with and without subtraction
=> increase numerical stability by subtracting a constant from the components

CHANGELOG.rst, docs/getting_started/intro/parameter.rst, tests/test_parameter.py, zfit/core/parameter.py
=> add explanation for jupyter of unique param names

CHANGELOG.rst, zfit/core/basemodel.py, zfit/core/loss.py, zfit/core/parameter.py
=> fix: autoconversion to complex parameter

CHANGELOG.rst, tests/test_fitresult.py, tests/test_minimizer.py, utils/api/argdocs.yaml, zfit/minimize.py, zfit/minimizers/minimizers_scipy.py
=> fix minimizers that have problems with gradient

tests/test_parameter.py, zfit/core/parameter.py
=> Fix warnings in test parameter.py

CHANGELOG.rst, zfit/minimizers/baseminimizer.py, zfit/minimizers/evaluation.py, zfit/minimizers/minimizer_nlopt.py, zfit/minimizers/strategy.py
=> Add loss to callbacks

CHANGELOG.rst, tests/test_loss.py, zfit/core/loss.py, zfit/minimizers/fitresult.py
Fixes #
- fixed loss string bug
- extended loss with sample sizes up to 3 mio
=> fix: loss not working

requirements_dev.txt
Fixes build failure in readthedocs
-
-
=> wip: fix docbuild

examples/simple_fit.py, zfit/util/cache.py
Fixes numpy arrays with objects need explicit dtype object
=> fix: update np.array explicit object dtype

CHANGELOG.rst, zfit/minimizers/evaluation.py, zfit/minimizers/fitresult.py, zfit/minimizers/minimizer_minuit.py
=> fix false positive fit result

CHANGELOG.rst, tests/test_loss.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/util/execution.py
- makes the loss callable
- two tests to check the callability and the compatibility with iminuit
=> enh: add callable method to loss

CHANGELOG.rst, tests/test_fitresult.py, zfit/minimizers/fitresult.py
- add a freeze method in order to pickle the results
- test the freeze and pickle/unpickle it
=> enh: add freeze to result to make fitresult pickleable

CHANGELOG.rst, requirements.txt
=> enh: add TensorFlow 2.6 support

.github/workflows/ci.yml, .readthedocs.yaml, CHANGELOG.rst, requirements.txt, requirements_dev.txt, setup.cfg, setup.py, tests/test_fitresult.py, tests/test_math.py, tests/test_minimizer.py, tests/test_pdf_conditional.py, zfit/__init__.py, zfit/minimizers/fitresult.py, zfit/models/conditional.py
Fixes #
- adds the GHA coveralls
- reactivate MacOS tests
- add windows tests
=> ci: use GHA coveralls, reactivate macos tests

CHANGELOG.rst, docs/conf.py, docs/index.rst, docs/tutorials/components/intro/model.rst, docs/tutorials/guides/index.rst, docs/tutorials/introduction.rst, docs/user_api/zfit.loss.rst, requirements_dev.txt, zfit/loss.py
=> docs: embed youtube, enhance title page

CHANGELOG.rst, tests/test_parameter.py, zfit/core/parameter.py
=> fix parameter not deleted

zfit/core/parameter.py, zfit/core/space.py
=> chore: remove deprecations

.github/workflows/ci.yml, CHANGELOG.rst, zfit/models/physics.py
Fixes #350 
- fix the wrong lower/upper limit in DCB integral
=> fix: correct lower and upper limits in DCB integral

CHANGELOG.rst, tests/test_fitresult.py, zfit/core/parameter.py, zfit/minimizers/fitresult.py, zfit/z/math.py
Allows to dump a fitresult and to set them saved values again
- Added pickling of the result
=> feat: allow to set parameters from dumped fitresult

CHANGELOG.rst, tests/test_binnedpdf.py, zfit/_loss/binnedloss.py, zfit/core/loss.py, zfit/models/unbinnedpdf.py
=> WIP: fix binned space

CHANGELOG.rst, requirements.txt, setup.py, zfit/minimizers/ipopt.py, zfit/minimizers/minimizer_nlopt.py, zfit/util/checks.py
- makes ipyopt and nlopt an optional dependency
=> enh: add runtime dependency and remove dependency of minimizers

CHANGELOG.rst, tests/test_data.py, zfit/core/data.py
Fixes long awaited possibility to have limits when loading from root
- extended data tests with limits
=> feat: add possibility for limits in `from_root` constructor

docs/_static/css/custom.css, docs/conf.py, docs/make_docs.sh, requirements_dev.txt, zfit/core/loss.py, zfit/exception.py, zfit/minimizers/fitresult.py, zfit/models/kde.py, zfit/util/improved_sheather_jones.py
Pydata now has a dark mode as well, that changed how colors are specified
=> WIP: fix docs theme

.github/dependabot.yml, CHANGELOG.rst, docs/user_api/zfit.constraint.rst, docs/user_api/zfit.param.rst, zfit/models/physics.py, zfit/models/polynomials.py, zfit/sample.py, zfit/util/cache.py, zfit/z/zextension.py
Treats variables as tensors if it doesn't matter
=> enh: don't recompile if depends on parameters without state

CHANGELOG.rst, tests/model/test_unbinned_from_binned.py, zfit/models/binned_functor.py
Fixes an issue with the sum of histogram PDFs
=> fix typo in binned sum

.github/workflows/ci.yml, CHANGELOG.rst, tests/histmath/test_histograming.py, tests/model/test_unbinned_from_binned.py, tests/test_dimensions.py, tests/test_space.py, utils/api/argdocs.yaml, zfit/core/binnedpdf.py, zfit/core/space.py
- use list of integers to get RegularBinning automatically
=> Allow multidimensional regular binning with integers

.pre-commit-config.yaml, requirements.txt, requirements_dev.txt, tests/highstats/test_exact_yields.py
=> enh: upgrade to TensorFlow 2.11

CHANGELOG.rst, zfit/core/basemodel.py, zfit/core/binning.py, zfit/core/loss.py, zfit/core/space.py, zfit/core/tensorlike.py, zfit/minimizers/baseminimizer.py, zfit/models/unbinnedpdf.py, zfit/z/unstable.py
Fixes #443 
- Just using *args to circumvent the problem of ragged tensors
- None, existing failed
=> fix new numpy not converting non-rectangulars

docs/conf.py
Fixes failing docs https://github.com/pydata/pydata-sphinx-theme/issues/1220
=> fix: sphinx data theme bug

CHANGELOG.rst, utils/api/argdocs.yaml, zfit/core/basepdf.py, zfit/minimizers/fitresult.py, zfit/models/basic.py, zfit/models/conditional.py, zfit/models/convolution.py, zfit/models/dist_tfp.py, zfit/models/functor.py, zfit/models/kde.py, zfit/models/physics.py, zfit/models/polynomials.py, zfit/models/unbinnedpdf.py
- add extended as an init arg to all the pdfs
=> add extended as all args to pdfs

CHANGELOG.rst, tests/test_random_seed.py, zfit/settings.py, zfit/z/random.py
- added automatic numpy and backend set seed
- reproducibility test
=> fix: make seed reproducible

CHANGELOG.rst, tests/test_data.py, zfit/core/data.py
- allow to return and from pandas with weights
- raises better error if slicing with indices fails on data
- extended the data tests
=> enh: add weights for to and from pandas and better exception

CHANGELOG.rst, requirements.txt, setup.py
=> enh: allow uproot 5

README.rst
=> Update README.rst with installation instructions

CHANGELOG.rst, requirements.txt, tests/test_kde_funcs.py, tests/test_pdf_kde.py, zfit/models/kde.py
- test arrays in comb KDE longtests
=> fix KDE bandwidth as array

CHANGELOG.rst, tests/backend/test_caching_backend.py, tests/truth/hs3/sum3gauss.json, zfit/core/data.py, zfit/core/parameter.py, zfit/models/functor.py, zfit/z/zextension.py
Fixes params have been cached, the old TF problem...
=> fix: parameter caching

.github/workflows/ci.yml, CHANGELOG.rst, tests/test_pdf_cb.py, zfit/core/loss.py, zfit/minimizers/errors.py, zfit/models/physics.py, zfit/models/polynomials.py
- added a safe `where` to make
=> Fix crystalball integral

requirements.txt
=> WIP: remove iminuit restriction

.readthedocs.yaml, requirements.txt, zfit/models/convolution.py, zfit/models/interpolation.py, zfit/models/morphing.py, zfit/z/interpolate_spline.py
This allows zfit to be published again on conda-forge
-
-
=> chore: remove deprectade tensorflow-addons

.github/workflows/ci.yml, CHANGELOG.rst, pyproject.toml, requirements.txt, tests/conftest.py, zfit/core/binning.py, zfit/core/parameter.py, zfit/models/kde.py
=> WIP: upgrade to TensorFlow 2.13

CHANGELOG.rst, requirements.txt, tests/test_loss.py, utils/api/argdocs.yaml, zfit/_loss/binnedloss.py, zfit/core/loss.py, zfit/loss.py, zfit/minimizers/base_tf.py, zfit/minimizers/evaluation.py
=> add "full" option to loss value

CHANGELOG.rst, zfit/models/histmodifier.py, zfit/models/template.py
=> fix: histmodifier yield

.github/workflows/ci.yml, CHANGELOG.rst, docs/user_api/zfit.run.rst, requirements.txt, setup.cfg, zfit/data.py
=> TF 2.15, drop Python 3.8

.github/workflows/ci.yml, tests/backend/test_performance_graph.py, tests/test_binnedpdf.py, tests/test_cache.py, zfit/_loss/binnedloss.py, zfit/core/binnedpdf.py, zfit/core/data.py, zfit/core/integration.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/core/sample.py, zfit/core/space.py, zfit/minimizers/baseminimizer.py, zfit/minimizers/errors.py, zfit/minimizers/minimizer_nlopt.py, zfit/models/kde.py, zfit/models/morphing.py, zfit/models/physics.py, zfit/models/polynomials.py, zfit/util/cache.py, zfit/util/improved_sheather_jones.py, zfit/z/zextension.py
Fixes #
- Do not reset global graph if not needed (old relict)
- speed test for sum of DCB evaluation
=> reduce caching reset

.github/workflows/ci.yml, requirements_dev.txt, setup.py, tests/test_fitresult.py, tests/test_minimizer.py, tests/test_strategy.py
=> enh: ci upgrade, add mac m1 silicon

zfit/models/basic.py, zfit/z/numpy.py
Fixes https://github.com/zfit/zfit/issues/539
=> fix: remove bad analytic integral registration in Voigt

CHANGELOG.rst, examples/signal_bkg_mass_fit.py, tests/conftest.py, tests/test_fitresult.py, tests/test_graph.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/minimizers/baseminimizer.py, zfit/minimizers/fitresult.py, zfit/minimizers/minimizer_minuit.py, zfit/settings.py, zfit/util/execution.py, zfit/util/temporary.py
- use a `FitResult` to update the parameters temporarily
- enable experimentally that the fit does _not_ update the default parameters
- to test the effects
=> use result to update params

tests/test_loss.py, utils/api/argdocs.yaml, zfit/core/data.py, zfit/core/loss.py, zfit/exception.py
as title, to make sure it's clear what is wanted
=> fix: raise error if uncut data for loss not within PDF limits

CHANGELOG.rst, zfit/core/basemodel.py, zfit/core/binnedpdf.py
=> fix: backwards incompatible fixed_params

CHANGELOG.rst, tests/test_space.py, zfit/_variables/axis.py, zfit/core/space.py
Fixes #504 
- raise error if transform
=> fix: raise error for transformed axes

CHANGELOG.rst, zfit/__init__.py, zfit/core/data.py, zfit/core/loss.py, zfit/minimizers/ipopt.py, zfit/models/basic.py, zfit/util/ztyping.py
=> fix multithreading and minor bug

.readthedocs.yaml, docs/make_docs.sh
=> WIP: build rtd docs using uv

.pre-commit-config.yaml, CHANGELOG.rst, tests/dill/test_dill.py, tests/test_pdf_template.py, zfit/dill.py
- verify the dill dump to make sure it's loadable again
- dill load and dump tests
=> enh: improve the dill dumping and loading

CHANGELOG.rst, zfit/_data/binneddatav1.py, zfit/core/binnedpdf.py, zfit/data.py, zfit/models/binned_functor.py, zfit/models/histogram.py, zfit/models/morphing.py, zfit/models/template.py, zfit/pdf.py
- adds data constructors and basebinnedpdf to public API
=> fix namespaces

CHANGELOG.rst, utils/ci/install_test_tutorials.sh, zfit/core/loss.py
- binned fits didn' take the "full" argument properly into account
=> fix binned full argument

CHANGELOG.rst, zfit/__init__.py, zfit/core/loss.py, zfit/minimizers/minimizer_minuit.py
=> consistently compile all loss methods

CHANGELOG.rst, requirements.txt, zfit/core/constraint.py, zfit/core/data.py, zfit/core/loss.py, zfit/core/parameter.py, zfit/core/serialmixin.py, zfit/models/basefunctor.py, zfit/models/basic.py, zfit/models/cache.py, zfit/models/convolution.py, zfit/models/dist_tfp.py, zfit/models/functor.py, zfit/models/kde.py, zfit/models/physics.py, zfit/models/polynomials.py, zfit/models/truncated.py, zfit/models/unbinnedpdf.py, zfit/serialization/pdfrepr.py, zfit/serialization/serializer.py, zfit/serialization/spacerepr.py
Fixes #564 
- use the V1 compatibility module
=> deps: upgrade pydantic to v2

docs/index.rst, docs/whats_new/upgrade_guide_020.ipynb, tests/test_binnedloss.py, utils/api/argdocs.yaml, zfit/core/basepdf.py, zfit/models/basic.py, zfit/models/binned_functor.py, zfit/models/convolution.py, zfit/models/dist_tfp.py, zfit/models/functor.py, zfit/models/physics.py, zfit/models/polynomials.py, zfit/models/tobinned.py, zfit/models/truncated.py, zfit/models/unbinnedpdf.py
=> upgrade docs to 020+

.pre-commit-config.yaml, zfit/core/loss.py
=> fix: params in simpleloss

CHANGELOG.rst, docs/user_api/minimize/minimizers.rst, tests/test_minimizer.py, utils/api/argdocs.yaml, zfit/core/data.py, zfit/core/parameter.py, zfit/minimize.py, zfit/minimizers/evaluation.py, zfit/minimizers/minimizers_scipy.py
=> enh: add scipybfgs

CITATION.cff
=> add_citationcff

CHANGELOG.rst, docs/tutorials/components/intro/minimize.rst, examples/minimize_python_func.py, tests/fullexample/test_simple_binned.py, tests/model/test_binned_general.py, tests/test_fitresult.py, tests/test_minimizer.py, tests/test_strategy.py, zfit/core/baseobject.py, zfit/core/loss.py, zfit/core/space.py, zfit/minimize.py, zfit/minimizers/fitresult.py, zfit/minimizers/ipopt.py, zfit/minimizers/minimizer_nlopt.py, zfit/minimizers/minimizers_scipy.py
- pass through parameters properly in simple loss
- fix (revert) numpy limits
-
=> fix: pass params through

CHANGELOG.rst, requirements.txt
=> Relax TF and TFP version to be compatible with older versions

CHANGELOG.rst, zfit/core/loss.py, zfit/minimizers/minimizer_lm.py, zfit/minimizers/termination.py
Adds more stable and faster calculation for EDM, fixes an issue in LM minimizer
=> fix: edm calculation, LM minimizer

.github/workflows/ci.yml, CHANGELOG.rst, examples/signal_bkg_mass_extended_fit.py, pyproject.toml, src/zfit/core/data.py, src/zfit/minimizers/errors.py, src/zfit/minimizers/fitresult.py, tests/result/test_uncertainties.py, tests/test_data.py, tests/test_fitresult.py, utils/api/argdocs.yaml
=> Fix weighted hesse corrections
