requirements_dev.txt
Makes dependency handling easier overall (no conflicting deps). And it's usually not required to have a ==.
=> Require >= instead of == for requirements

requirements.txt, zfit/core/parameter.py
We inherit know from the better `ResourceVariable` instead of `Variable`. This works with tf 0.10+. Byebye old versions!
(CI is ok, the failing test is fixed in another PR, tested locally)
It's mostly FYI
=> TF forward compatibility

requirements.txt, zfit/util/logging.py
Logger configuration is added.
Pending question: should we add a `to_file` option that enables streaming to file, together with `to_screen`? This would only work for first instantiation, so it could cause confusion when used by a user. A solution to this would be to have a separate method: `log_to_file(logger_name, file_name, log_level)` which would inspect the handlers and add whatever was necessary, and something like `log_to_screen(logger, log_level)` that could be used to hide the printing to screen.
What do you think? @mayou36
=> Add basic logging

tests/test_basePDF.py, tests/test_data.py, tests/test_execution.py, tests/test_integrate.py, tests/test_loss.py, tests/test_minimizer.py, tests/test_operations.py, tests/test_parameter.py, tests/test_pdf_normal.py, tests/test_pdfs.py, tests/test_tfext.py, zfit/__init__.py, zfit/core/basemodel.py, zfit/core/basepdf.py, zfit/core/data.py, zfit/core/integration.py, zfit/core/minimizer.py, zfit/core/parameter.py, zfit/models/basic.py, zfit/models/dist_tfp.py, zfit/models/functor.py, zfit/pdf.py, zfit/settings.py, zfit/util/execution.py, zfit/util/graph.py
This PR adresses:
- introducing the RunManager that is responsible for: providing a `zfit.run`, default session, chunksize, cpu management etc
- adding some (WIP but will be done later) chunking for Integration
- changing the Gauss from the custom implementation to the TensorFlow Probability one (including analytic integration over the whole range)
- Removing of "session" from public view (at least for the Introductory Notebook) by providing lazy a default session and a `zfit.run` to run tensors, including automatic variable initialization (no more `tf.global_variables_initializer()`)
@apuignav ready to merge from me, no deep review required from my side (I just don't like to do solo-late-night-merges ;) ). The [notebook is updated as …
=> RunManager and small improvements

tests/test_basePDF.py, tests/test_integrate.py, tests/test_pdfs.py, zfit/core/basemodel.py, zfit/core/integration.py, zfit/core/limits.py, zfit/models/basic.py, zfit/models/physics.py
Introducing a shift in exp, leaving the pdf untouched and shifting x to around 0 for numerical stability (exp overflows otherwise)
Also changed analytic integral function API from
`func(limits, params)` 
to
`func(limits, params, model)` 
-> some code may breaks
=> Fix exponential pdf

tests/test_basePDF.py, tests/test_operations.py, tests/test_pdfs.py, tests/test_simple_subclass.py, zfit/core/basefunc.py, zfit/core/interfaces.py, zfit/core/operations.py, zfit/models/functions.py
=> Rename `Func.value` to `Func.func` without sideeffects

tests/test_space.py, zfit/core/limits.py
currently `limit1d` to return (lower, upper) for simple scalars
what other shortcut would be helpful, 1d with two limits? @apuignav
=> Simpler limits

zfit/core/parameter.py
Closes #108.
PS: I only fixed the "user-facing" kwargs, that is, from `Parameter` onwards.
=> Fix consistency of init_value.

zfit/models/physics.py
Fixes a simple typo in the Crystal Ball docstring.
=> Fix simple typo in docstring

tests/test_sampling.py, zfit/core/basemodel.py, zfit/core/limits.py, zfit/core/sample.py
Finally, there we go :)
If fixed limits are used with an event space, sampling from a PDF (currently n has to be specified still, although it is in principle redundant, but if it does not match, it raises an error) means repeating the accept reject until a candidate for each limit is found.
=> Sampling with fixed limits

zfit/minimizers/baseminimizer.py, zfit/minimizers/minimizer_minuit.py
Refactor how MinuitMinimizer handles the Parameters internally. Allows to deal with a single parameter holding several values (for speed comparison and pyhf compatibility)
=> Refactor Minuit parameter handling

zfit/core/basemodel.py
Small bug fix: test if norm_range is False but it's not the methods responsibility (and does it wrong therefore)
=> Remove catch of norm_range limits False, wrong responsibility

tests/test_constraint.py, tests/test_loss.py, zfit/constraint.py, zfit/ztf/__init__.py, zfit/ztf/wrapping_tf.py
nll_gaussian can now take as input for the `sigma` argument either a list of standard deviations or a covariance matrix.
None, already implemented tests are working.
=> More general nll_gaussian constraint

docs/loss.rst, docs/model.rst, tests/test_constraint.py, tests/test_loss.py, zfit/constraint.py, zfit/core/constraint.py, zfit/core/loss.py
Creation of constraints object
- Creation of `BaseConstraint` depending only on `BaseNumeric`
- Creation of `SimpleConstraint` that can take tensor
- Creation of `DistributionConstraint` that can tfp pdfs, samples of constrained parameters possible
- Creation of `GaussianConstraint` depending on `DistributionConstraint` 
Modification of tests in `test_loss.py` and `test_constraint`.
=> Add new constraint classes

docs/loss.rst, docs/model.rst, tests/test_sampling.py, zfit/core/data.py
Fixes#
- `param_values` was not taken into account before in the function.
- also some fixes for the constraint documentation look 
add tests using `param_values` argument in `test_sampling.py`
=> Fix resample method when using param_values argument

requirements.txt, tests/test_basePDF.py, tests/test_dependents.py, tests/test_parameter.py, zfit/core/baseobject.py, zfit/core/parameter.py, zfit/util/ztyping.py
Fixes #166
- use ordered-set package to preserve the order
-
=> ordered dependents

setup.py
Tensorflow2 does not yet support python38 and the error message
when trying to install with pip and python38 is more helpful if
we restrict it too.
* Example of error message with restriction:
`zfit requires Python '>=3.6, <3.8' but the running Python is
3.8.0`
* Without restriction:
`Could not find a version that satisfies the requirement
tensorflow>=2`
Fixes #
- Change `python_requires` string.
None
=> Restrict python version to be strictly smaller than 3.8

zfit/__init__.py
On each run of zfit there is a warning displayed about the switch to
tensorflow2. Two things were disturbing:
1. The message was weirdly formatted due to the triple quoted string usage.
This was fixed by using inspect.cleandoc() to remove indents in the string.
2. The last line of the message would be displayed twice, because
warnings.warn() shows the line where the warning is thrown. This was fixed
by using the argument `stacklevel=2`. The warning now shows
`import zfit` as the point of error.
Fixes #
-
-
-
-
-
-
=> Make warning about switch to tensorflow2 a bit nicer.

tests/test_dependents.py
The pytest test_get_dependents_ordered() tested that the
outcome of list(OrderedDict) != list(set(OrderedDict)).
This is not a guaranteed behavior of the python set() and
list() functions, although it often will be the case.
The actual intention of the test function was to test
whether pdf.get_dependents() would return the same
OrderedDict on each subsequent call, i.e. whether the
function is deterministic. The test function has
been rewritten to reflect that intent.
Fixes #
-
-
-
-
-
-
=> Fix test_get_dependents_ordered() and rename to test_get_dependents_is_deterministic()

tests/test_fitresult.py, tests/test_minimizer.py, zfit/minimizers/fitresult.py
* fixes error from `hesse_np` function
* In the `hesse` method, the hessian matrix is now computed using all the free parameters in the fit, leading to the same results between using `hesse_np` and `minuit_hesse` methods when using the `params` argument
* makes `covariance` available for any minimizers
* One test to check that errors from `hesse_np` and `minuit_hesse` are similar.
=> Fix hesse_np and add covariance for any minimizer

docs/intro/loss.rst
- Fixes the example for GaussianConstraint in the documentation as the keyword arguments were renamed in the constructor.
=> Fix GaussianConstraint example

CHANGELOG.rst, tests/test_loss.py, tests/test_minimizer.py, zfit/core/loss.py, zfit/minimizers/baseminimizer.py
What should be the behavior of a parameter, not floating, that is _explicitly_ given to `minimizer.minimize(..., params=[..., non_floating_param,...])?
This changes that if a parameter is not floating it won't be used even if explicitly given. Can though fail, better raise an error?
UPDATE: The behavioral way to go seems to be that:
- any parameter (object) given will be used in the fit, whether it is independent or not (in the latter case, the independent params will be extracted and used in the fit). Furthermore, any _explicit_ given parameter will, if possible, be given to the minimizer as well and printed as a "fixed" parameter. This includes independent and non-floating parameters as well as dependent parameters. Open: should non-floating independent parameter that are dependencies …
=> WIP: Behavior of floating param given to `minimize`

zfit/core/baseobject.py
=> Delete unused module variable _COPY_DOCSTRING.

CHANGELOG.rst, tests/test_pdf_poisson.py, zfit/models/dist_tfp.py, zfit/pdf.py
- Add the Poisson PDF, this will be useful for analysts who want to do inferences with `hepstats`  with counting analysis instead of shape analysis (see https://github.com/scikit-hep/hepstats/pull/33). And maybe for other cases ... 🤷🏻‍♂️
- test_pdf_poisson.py
=> Addition of Poisson 

CHANGELOG.rst, docs/plots/fftconv_spline_linear.py, requirements.txt, tests/test_pdf_fftconv.py, tests/test_pdf_kde.py, tests/test_pdf_polynomials.py, tests/test_sampling.py, zfit/core/basemodel.py, zfit/core/data.py, zfit/core/sample.py, zfit/models/convolution.py, zfit/models/functor.py, zfit/pdf.py
Adds a one dimensional convolution PDF
- add a discrete/FFT convolution (using `tf.nn.convolution`) and interpolate (linear/splines)
- multiple to check for sampling (special, just adding the dataset) and shape against `scipy.signal.convolve`
=> FFT convolution PDF

CHANGELOG.rst, tests/test_pdf_poisson.py, zfit/models/dist_tfp.py
Fixes #275, at least regarding the `Poisson` PDF side.
`tf.identity` works on a tensor ;).
Replace 
```python3
dist_params = dict(rate=lamb)
```
with
```python3
dist_params = lambda: dict(rate=lamb.value())
```
- Duplication of the existing test with a `ComposedParameter` as the `rate` argument of `Poisson`.
=> Modification of Poisson PDF to solve #275

tests/test_pdf_fftconv.py
The test `test_onedim_sampling` is flaky. This PR fixes this issue.
To find a solution, I collected samples of the pvalue from several test executions and computed the tail distribution. I computed the extreme percentiles to check how high can the values be.
```
0.9::1.5e-05
0.99::1.22e-07
0.9999::2.29e-8 ~ 1e-8
```
For this fix, I chose the 99.99th percentile. I think setting the bound using the statistical evaluation might be a good way to ensure the test is not flaky.
Do you guys think this makes sense? Please let me know if this looks good or if you have any other suggestions. Also, here I assume there are no bugs in the code under test.
=> Fixing Flaky test

docs/_static/css/custom.css
White color was applied to all elements with class .nav-link instead of only the ones inside a .navbar-nav element.
This caused the links in the right column to turn white as well, making them invisible on the white background.
=> Fix css bug

CHANGELOG.rst, tests/test_fitresult.py, tests/test_minimizer.py, tests/test_parameter.py, zfit/core/parameter.py, zfit/minimizers/errors.py, zfit/minimizers/evaluation.py, zfit/minimizers/fitresult.py, zfit/minimizers/ipopt.py, zfit/minimizers/minimizer_minuit.py, zfit/minimizers/minimizer_nlopt.py, zfit/minimizers/minimizer_tfp.py, zfit/minimizers/minimizers_scipy.py, zfit/z/math.py
Fixes #188
- `set_value` now raises an error if out of limits. Added `assign` that does not throw.
-
=> parameter raises error with `set_value` out of limits

.github/workflows/cd.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, CHANGELOG.rst, setup.cfg, zfit/__init__.py
=> enh: drop Python 3.6 support

zfit/__init__.py
- The logic in _maybe_disable_warnings() did not actually do what
the warning about the suppression of TensorFlow warnings claimed.
Setting the environment variable had no effect.
- Also slightly simplified the wording of the warning.
=> Fix handling of ZFIT_DISABLE_TF_WARNING environment variable.

CHANGELOG.rst, tests/test_loss.py, utils/api/argdocs.yaml, zfit/core/interfaces.py, zfit/core/loss.py
Allows to simply create a new instance of the loss
- `add create_new method to loss`
- for the method
=> add create_new method to loss

setup.py, zfit/minimizers/ipopt.py
=> fix: remove ipyopt requirement from macos

docs/getting_started/intro/data.rst, docs/getting_started/intro/loss.rst, docs/getting_started/intro/minimize.rst, docs/getting_started/intro/model.rst, docs/getting_started/intro/result.rst, docs/getting_started/intro/toy_studies.rst
While going through the documentation, specifically the intro section, I noticed some minor typos. I probably missed some but here are the ones that I found and fixed.
=> Fix typos in the intro guide

CHANGELOG.rst, requirements_dev.txt, tests/test_minimizer.py, zfit/minimizers/minimizers_scipy.py
=> fix:  use BFGS as default if no hessian is given

CHANGELOG.rst, docs/getting_started/5_minutes_to_zfit.rst, tests/test_pdf_cb.py, zfit/core/testing.py, zfit/models/physics.py
Fixes a minus sign in the wrong place and vectorizes the integral computation.
=> enh: vectorize dcb integral with where not case

CHANGELOG.rst, tests/fullexample/test_simple_binned.py, tests/test_fitresult.py, tests/test_minimizer.py, zfit/minimizers/fitresult.py, zfit/minimizers/interface.py, zfit/minimizers/minimizer_minuit.py, zfit/minimizers/minimizer_nlopt.py, zfit/minimizers/minimizers_scipy.py, zfit/util/warnings.py
- the default name of the uncertainty methods `hesse` and `errors` depended on
the method used (such as 'minuit_hesse', 'zfit_errors' etc.) and would be the exact method name.
New names are now 'hesse' and 'errors', independent of the method used. This reflects better that the
methods, while internally different, produce the same result.
To update, use 'hesse' instead of 'minuit_hesse' or 'hesse_np' and 'errors' instead of 'zfit_errors'
or 'minuit_minos' in order to access the uncertainties in the fitresult.
Currently, the old names are still available for backwards compatibility.
If a name was explicitly chosen in the error method, nothing changed.
=> change of default error name

CHANGELOG.rst, tests/test_z.py, zfit/z/random.py
Fixes #377 
- use the dynamic `get_shape`, otherwise it's hardcoded after the tracing
-
=> fix: use dynamic shape in decorated multinomial func

CHANGELOG.rst, zfit/minimizers/fitresult.py
- Increase precision in result preview of value and add a remark that the value is rounded
-
=> fix: enhance precision of fitresult param values

CHANGELOG.rst, zfit/core/sample.py, zfit/settings.py, zfit/z/tools.py
- Use public method in extended sampling to get the samples of the individual pdfs
=> WIP: fix extended sampling was using internal method

.pre-commit-config.yaml, CHANGELOG.rst, tests/test_binnedloss.py, zfit/_loss/binnedloss.py
Simultaneous binned fit
- sum over all dimensions in the binned fits would fail with different binnings because a dimension was not summed over and therefore mismatched
- add simultaneous test with different binnings
=> fix: simultaneous binned fits correctly sum over all dimensions

requirements.txt, zfit/__init__.py
[`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html) is preferred over the older `pkg_resources`. The current setup with `pkg_resources` [also causes CI problems](https://github.com/ComPWA/compwa-org/runs/6612064353?check_suite_focus=true#step:5:210).
See also https://github.com/zfit/phasespace/issues/80
=> build: set zfit version with importlib-metadata

CHANGELOG.rst, requirements.txt, tests/test_data.py, zfit/core/data.py, zfit/util/execution.py
Needed for caching as in #405 
- adds an eager caching method, namely a `hashint` attribute to unbinned datasets. Resampleable datasets are not hashable.
- checking the invalidation of the hashint
=> add hash functionality to dataset

CHANGELOG.rst, examples/binned_template_simple.py, examples/minimize_python_func.py, examples/plot_sig_bkg.py, examples/signal_bkg_mass_extended_fit_binned.py, tests/conftest.py, tests/test_cache.py, tests/test_graph.py, tests/test_minimizer.py, zfit/core/data.py, zfit/util/cache.py, zfit/util/execution.py, zfit/z/math.py, zfit/z/zextension.py
- add a cachsize option that limits how many compiled tf.functions are remembered. This will solve widespread problems of memory leaks, but *can* potentially remove too many cachings, in which case the function would be recompiled on every occasion.
=> clean graph more frequently to reduce memory leaks and overall usage

.github/workflows/ci.yml, CHANGELOG.rst, examples/signal_bkg_mass_extended_fit_binned.py, tests/conftest.py, tests/fullexample/test_binned_vs_unbinned.py, tests/highstats/test_exact_yields.py, tests/test_binnedloss.py, tests/test_binnedpdf.py, tests/test_data.py, tests/test_fitresult.py, tests/test_minimizer.py, tests/test_sampling.py, utils/api/argdocs.yaml, zfit/_data/binneddatav1.py, zfit/_loss/binnedloss.py, zfit/core/basemodel.py, zfit/core/basepdf.py, zfit/core/binnedpdf.py, zfit/core/binning.py, zfit/core/data.py, zfit/core/interfaces.py, zfit/core/loss.py, zfit/models/convolution.py, zfit/models/tobinned.py, zfit/util/cache.py, zfit/z/random.py, zfit/z/zextension.py
Fixes #
- implement create_sampler for the binned pdf
- Testing of sampler vs normal sample
- test fit of unbinned fit vs binned fit
=> Implementing missing methods: create_sampler, to_binned, to_unbinned

requirements.txt
Currently on macos with Apple Sillicon (I don't know if it's the same with x86 macs), zfit is uninstallable via pip just because tensorflow isn't available as "tensorflow" on pypi but as "tensorflow-macos".
```
iason@quiet:~$ virtualenv test --python=3.10
created virtual environment CPython3.10.10.final.0-64 in 182ms
creator CPython3Posix(dest=/Users/iason/test, clear=False, no_vcs_ignore=False, global=False)
seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/iason/Library/Application Support/virtualenv)
added seed packages: pip==23.0.1, setuptools==67.1.0, wheel==0.38.4
activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
iason@quiet:~$ source test/bin/activate
(test) …
```
=> Fix pip install on arm64 macs

CHANGELOG.rst, tests/test_data.py, zfit/core/data.py, zfit/z/zextension.py
- fix that `unstack_x` inhibits again legacy behavior
- extended testdata
=> fix: shape of unstack_x with an obs

CHANGELOG.rst, requirements_dev.txt, tests/backend/test_caching_backend.py, tests/backend/test_performance_graph.py, tests/test_loss.py, zfit/core/parameter.py, zfit/models/physics.py, zfit/util/cache.py, zfit/util/container.py, zfit/z/zextension.py
Fixes #592 
- Use the hash of the parameter as an `alias_id` in the parameter spec for a placeholder. Before, it was None (follows closely the tf.Variable behavior)
- check that using the same parameter for multiple arguments works both with tf.function and z.function
=> fix: handle multiple same zfit.Parameter instances properly in tf.function

CHANGELOG.rst, tests/data/test_binneddata.py, tests/data/test_binneddata_sampler.py, tests/data/test_samplerdata.py, tests/model/test_pdf_histogram.py, tests/model/test_pdf_params_args.py, tests/model/test_truncated_pdf.py, tests/test_data.py, tests/test_pdf_bifurgauss.py, tests/test_pdf_conditional.py, tests/test_pdf_gamma.py, tests/test_pdf_johnsonsu.py, tests/test_pdf_polynomials.py, tests/test_pdf_qgauss.py, zfit/_data/binneddatav1.py, zfit/core/data.py, zfit/core/interfaces.py, zfit/core/loss.py, zfit/minimizers/errors.py, zfit/models/conditional.py
- allow zfit data to update sampler
- add `samplesize` and `num_entries` attribute to replace `nevents` (ambiguous) for data
- test the new attributes
=> Enh: allow zfit data to update sampler

CHANGELOG.rst, examples/signal_bkg_mass_extended_fit_binned.py, tests/data/test_binneddata_sampler.py, zfit/_data/binneddatav1.py, zfit/core/interfaces.py, zfit/core/loss.py
Allows `BinnedSamplerData` to be constructed from hist
Fixes stability in BinnedNLL
=> fix:  number of entries in binned case for NLL subtraction and BinnedSampler

CHANGELOG.rst, src/zfit/minimizers/fitresult.py, tests/test_fitresult.py
- Add _is_frozen flag to prevent double freezing
- Return early from freeze() if already frozen
- Add test to verify double freeze behavior
- Update changelog with fix
Fixes #632
=> Fix AttributeError when calling freeze() twice on FitResult
